console.log('Thank you for installing Lodge CLI');
console.log('Run "lodge init" to get started');
console.log('Run "lodge help" for more information');
console.log('          ^');
console.log('        /  \\');
console.log('       / ---\\');
console.log('      /      \\');
console.log('     / -------\\');
console.log('    /          \\');
console.log('--  -------  ---\\');
console.log('                 \\');
console.log('----  ------------\\');
console.log('                    ');
console.log('------  ------------');
console.log('');
console.log('--------------------');